# Face Feature Recognition

# Step 1: Loading and presenting an image

In [1]:
import cv2

In [2]:
# read the image
img = cv2.imread("E:/face.jpeg")# read the image
img = cv2.imread("E:/face.jpeg")

In [3]:
# show the image
cv2.imshow(winname="Face",mat=img)

In [6]:
# wait for a key press to exit
cv2.waitKey(delay=0)

-1

In [7]:
# close all windows
cv2.destroyAllWindows()

# Step 2: Face recognition

In [8]:
import cv2
import dlib

In [10]:
# load the detector
detector = dlib.get_frontal_face_detector()

In [11]:
# read the image
img = cv2.imread("E:/face.jpeg")

In [12]:
# Convert image into grayscale
gray = cv2.cvtColor(src=img, code=cv2.COLOR_BGR2GRAY)

In [13]:
# Use detector to find landmarks
faces = detector(gray)

In [14]:
for face in faces:
    x1 = face.left() # left point
    y1 = face.top() # top point
    x2 = face.right() # right point
    y2 = face.bottom() # bottom point
    # Draw a rectangle

In [16]:
# Draw a rectangle
cv2.rectangle(img=img, pt1=(x1, y1), pt2=(x2, y2), color=(0, 255, 0), thickness=4)

array([[[111, 134, 156],
        [111, 134, 156],
        [111, 134, 156],
        ...,
        [ 59,  54, 109],
        [ 49,  44,  99],
        [ 46,  41,  96]],

       [[110, 133, 155],
        [110, 133, 155],
        [110, 133, 155],
        ...,
        [ 59,  54, 109],
        [ 48,  43,  98],
        [ 45,  40,  95]],

       [[109, 132, 154],
        [109, 132, 154],
        [109, 132, 154],
        ...,
        [ 60,  55, 110],
        [ 49,  44,  99],
        [ 46,  41,  96]],

       ...,

       [[ 81,  34,  30],
        [ 79,  32,  28],
        [ 77,  30,  26],
        ...,
        [201,  78,  74],
        [201,  78,  74],
        [201,  78,  74]],

       [[ 81,  34,  30],
        [ 79,  32,  28],
        [ 77,  30,  26],
        ...,
        [202,  79,  75],
        [201,  78,  74],
        [201,  78,  74]],

       [[ 82,  35,  31],
        [ 80,  33,  29],
        [ 77,  30,  26],
        ...,
        [203,  80,  76],
        [202,  79,  75],
        [203,  80,  76]]

In [17]:
# show the image
cv2.imshow(winname="Face", mat=img)

In [18]:
# Wait for a key press to exit
cv2.waitKey(delay=0)

-1

In [19]:
# Close all windows
cv2.destroyAllWindows()

# Step 3: Identifying face features

In [20]:
import cv2
import dlib

In [21]:
# Load the detector
detector = dlib.get_frontal_face_detector()

In [22]:
# Load the predictor
predictor = dlib.shape_predictor("E:/shape_predictor_68_face_landmarks.dat")# Load the predictor
predictor = dlib.shape_predictor("E:/shape_predictor_68_face_landmarks.dat")

In [23]:
# read the image
img = cv2.imread("E:/face.jpeg")

In [24]:
# Convert image into grayscale
gray = cv2.cvtColor(src=img, code=cv2.COLOR_BGR2GRAY)

In [25]:
# Use detector to find landmarks
faces = detector(gray)

In [26]:
for face in faces:
    x1 = face.left() # left point
    y1 = face.top() # top point
    x2 = face.right() # right point
    y2 = face.bottom() # bottom point

In [28]:
# Look for the landmarks
landmarks = predictor(image=gray, box=face)
x = landmarks.part(27).x
y = landmarks.part(27).y

In [29]:
# Draw a circle
cv2.circle(img=img, center=(x, y), radius=5, color=(0, 255, 0), thickness=-1)

array([[[111, 134, 156],
        [111, 134, 156],
        [111, 134, 156],
        ...,
        [ 59,  54, 109],
        [ 49,  44,  99],
        [ 46,  41,  96]],

       [[110, 133, 155],
        [110, 133, 155],
        [110, 133, 155],
        ...,
        [ 59,  54, 109],
        [ 48,  43,  98],
        [ 45,  40,  95]],

       [[109, 132, 154],
        [109, 132, 154],
        [109, 132, 154],
        ...,
        [ 60,  55, 110],
        [ 49,  44,  99],
        [ 46,  41,  96]],

       ...,

       [[ 81,  34,  30],
        [ 79,  32,  28],
        [ 77,  30,  26],
        ...,
        [201,  78,  74],
        [201,  78,  74],
        [201,  78,  74]],

       [[ 81,  34,  30],
        [ 79,  32,  28],
        [ 77,  30,  26],
        ...,
        [202,  79,  75],
        [201,  78,  74],
        [201,  78,  74]],

       [[ 82,  35,  31],
        [ 80,  33,  29],
        [ 77,  30,  26],
        ...,
        [203,  80,  76],
        [202,  79,  75],
        [203,  80,  76]]

In [30]:
# show the image
cv2.imshow(winname="Face", mat=img)


In [31]:
# Wait for a key press to exit
cv2.waitKey(delay=0)

-1

In [32]:
# Close all windows
cv2.destroyAllWindows()

# Render all the points in the landmark

In [33]:
import cv2
import numpy as np
import dlib

In [34]:
# Load the detector
detector = dlib.get_frontal_face_detector()

In [35]:
# Load the predictor
predictor = dlib.shape_predictor("E:/shape_predictor_68_face_landmarks.dat")

In [36]:
# read the image
img = cv2.imread("E:/face.jpeg")

In [37]:
# Convert image into grayscale
gray = cv2.cvtColor(src=img, code=cv2.COLOR_BGR2GRAY)

In [38]:
# Use detector to find landmarks
faces = detector(gray)
for face in faces:
    x1 = face.left() # left point
    y1 = face.top() # top point
    x2 = face.right() # right point
    y2 = face.bottom() # bottom point

In [39]:
# Create landmark object
landmarks = predictor(image=gray, box=face)

In [40]:
# Loop through all the points
for n in range(0, 68):
        x = landmarks.part(n).x
        y = landmarks.part(n).y

In [41]:
# Draw a circle
cv2.circle(img=img, center=(x, y), radius=3, color=(0, 255, 0), thickness=-1)

array([[[111, 134, 156],
        [111, 134, 156],
        [111, 134, 156],
        ...,
        [ 59,  54, 109],
        [ 49,  44,  99],
        [ 46,  41,  96]],

       [[110, 133, 155],
        [110, 133, 155],
        [110, 133, 155],
        ...,
        [ 59,  54, 109],
        [ 48,  43,  98],
        [ 45,  40,  95]],

       [[109, 132, 154],
        [109, 132, 154],
        [109, 132, 154],
        ...,
        [ 60,  55, 110],
        [ 49,  44,  99],
        [ 46,  41,  96]],

       ...,

       [[ 81,  34,  30],
        [ 79,  32,  28],
        [ 77,  30,  26],
        ...,
        [201,  78,  74],
        [201,  78,  74],
        [201,  78,  74]],

       [[ 81,  34,  30],
        [ 79,  32,  28],
        [ 77,  30,  26],
        ...,
        [202,  79,  75],
        [201,  78,  74],
        [201,  78,  74]],

       [[ 82,  35,  31],
        [ 80,  33,  29],
        [ 77,  30,  26],
        ...,
        [203,  80,  76],
        [202,  79,  75],
        [203,  80,  76]]

In [45]:
# show the image
cv2.imshow(winname="Face", mat=img)

In [46]:
# Delay between every fram
cv2.waitKey(delay=0)

-1

In [47]:
# Close all windows
cv2.destroyAllWindows()

# Step 4: Real-time detection

In [48]:
import cv2
import dlib

In [49]:
# Load the detector
detector = dlib.get_frontal_face_detector()

In [50]:
# Load the predictor
predictor = dlib.shape_predictor("E:/shape_predictor_68_face_landmarks.dat")

In [ ]:
# read the image
cap = cv2.VideoCapture(0)

while True:
    _, frame = cap.read()

In [ ]:
# Convert image into grayscale
gray = cv2.cvtColor(src=frame, code=cv2.COLOR_BGR2GRAY)

In [ ]:
# Use detector to find landmarks
faces = detector(gray)

In [ ]:
for face in faces:
        x1 = face.left()  # left point
        y1 = face.top()  # top point
        x2 = face.right()  # right point
        y2 = face.bottom()  # bottom point

In [ ]:
# Create landmark object
landmarks = predictor(image=gray, box=face)

In [ ]:
# Loop through all the points
for n in range(0, 68):
     x = landmarks.part(n).x
    y = landmarks.part(n).y

In [ ]:
# Draw a circle
cv2.circle(img=frame, center=(x, y), radius=3, color=(0, 255, 0), thickness=-1)

In [ ]:
# show the image
cv2.imshow(winname="Face", mat=frame)

In [ ]:
# Exit when escape is pressed
    if cv2.waitKey(delay=1) == 27:
        break

In [ ]:
# When everything done, release the video capture and video write objects
cap.release()

In [ ]:
# Close all windows
cv2.destroyAllWindows()